url: http://urbar.imcontec.eu
title: Urbariát a pasienkové spoločenstvo v Dulovej Vsi
description: Urbariát Dulova Ves - verejné informácie

github:
  is_project_page: false

# Display breadcrumbs at all?
breadcrumb_display: true

# Display Home path in breadcrumb?
breadcrumb_home_display: true

# Url for Home path to point to
breadcrumb_home_url: http://urbar.imcontec.eu

# Display name for "Home" path
breadcrumb_home_name: Home
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
