theme: minima

minima:
  date_format: "%d. %m. %Y"
  skin: dark
  
#url: http://urbar.imcontec.eu
title: Urbariát
description: Urbariát Dulova Ves - verejné informácie

github:
  is_project_page: false

header_pages:
  - about.md
  - news.md
  - docs.md
  - contacts.md



#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
