theme: minima

minima:
  date_format: "%d. %m. %Y"
  skin: dark


title: Urbariát Dulova Ves
description: Urbariát Dulova Ves - verejné informácie
show_excerpts: true

#url: http://urbar.imcontec.eu

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
github:
  is_project_page: false

header_pages:
  - about.md
  - orgStructure.md
  - docs.md
  - contacts.md



#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
