title: Urbariát Dulova Ves
#description: Urbariát Dulova Ves - verejné informácie
description: >
  Toto je úvodná verzia web lokality Urbariátu Dulova Ves, ktorej
  cieľom je zlepšiť informovanosť podielnikov tohto urbariátneho
  spoločenstva. Dopredu Vám ďakujeme za návrhy na akékoľvek zlepšenia,
  alebo opravu chýb.

author:
  name: Ing. Matus Ivanecky
  email: matus.ivanecky@gmail.com

minima:
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%d. %m. %Y"

  social_links:
    - { platform: twitter,              user_url: "https://twitter.com/urbarDulova" }

show_excerpts: true

#url: http://urbar.imcontec.eu

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
header_pages:
  - about.md
  - orgStructure.md
  - docs.md
  - contacts.md


remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
