#url: http://urbar.imcontec.eu
title: Urbariát Dulova Ves
description: >
 Týmto projektom sa snažíme zlepšiť informovanie v rámci spoločenstva. Vaše návrhy a podnety nám posielajte na [email]. Ďakujeme!"
url: "https://urbar.dulovaves.sk"
lang: sk_SK
nomarkdown: true

paginate: 5

#feed_items: 10
#feed_update_period: daily
#feed_update_frequency: 1

exclude: [vendor]

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: urbariat-dulova-ves

author:
  name: Ing. Matus Ivanecky
  email: matus.ivanecky@gmail.com

minima:
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%d. %m. %Y"

  #social_links:
  #  - { platform: twitter,              user_url: "https://twitter.com/urbarDulova" }

show_excerpts: true

header_pages:
  - about.md
  - orgStructure.md
  - docs.md
  - docs.md#projekty
  - historia.md
  - contacts.md
  

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship
  - ./_plugins/jekyll-alerts-tag.rb

remote_theme: jekyll/minima
