url: http://urbar.imcontec.eu
title: Urbariát a pasienkové spoločenstvo v Dulovej Vsi
description: Urbariát Dulova Ves - verejné informácie

github:
  is_project_page: true

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
